env:
  browser: false
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
overrides: []
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
